swagger: "2.0"
info:
  version: "0.0.1"
  title: "Common User API"
  description: "Common User API"

schemes:
  - "http"
  - "https"

paths:
  /common/signup:
    post:
      summary: "Store a user"
      description: "Stores authentication creedentials and user relevant informations to a store"
      operationId: "signup"
      consumes:
        - "application/json"
      parameters:
        - name: "user"
          in: "body"
          description: "User object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/User"
      responses:
        201:
          description: "User registrated successfuly"
  /common/resetPassword/{userName}:
    post:
      summary: "Sends a reset password notification for a user"
      description: "Sends a reset password notification for a user"
      operationId: "sendConfirmation"
      consumes:
        - "application/json"
      parameters:
        - name: "userName"
          in: "path"
          description: "Username of user"
          required: true
          type: "string"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "User not found"
  /common/resetPassword/{token}:
    get:
      summary: "Resets password for a user"
      description: "Resets password for a user"
      operationId: "resetPassword"
      parameters:
        - name: "token"
          in: "path"
          description: "UUID token of reset passwword"
          required: true
          type: "string"
          format: "uuid"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Token not found"