swagger: "2.0"
info:
  version: "0.0.1"
  title: "Role Management API"
  description: "Role Management API"

basePath: "/v1/api"
schemes:
  - "http"
  - "https"

produces:
  - "application/json"

paths:
  /rolemanagement/role:
    get:
      summary: "Retrieves all roles"
      description: "Returns all roles from a store"
      operationId: "getRoles"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: array
            items:
              type: string