swagger: "2.0"
info:
  version: "0.0.1"
  title: "Signup API"
  description: "Signup API"

schemes:
  - "http"
  - "https"

paths:
  /signup:
    post:
      summary: "Store a user"
      description: "Stores authentication creedentials and user relevant informations to a store"
      operationId: "signup"
      consumes:
        - "application/json"
      parameters:
        - name: "user"
          in: "body"
          description: "User object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/User"
      responses:
        201:
          description: "User registrated successfuly"