INSERT INTO USER_AUTH_DETAILS VALUES (
  'admin', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_ADMIN'
);
INSERT INTO USER_DETAILS VALUES (
  'admin', 'Mate', 'Karolyi', 27, 'test1@opx.hu'
);

INSERT INTO USER_AUTH_DETAILS VALUES (
  'user1', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_USER'
);
INSERT INTO USER_DETAILS VALUES (
  'user1', 'Gergo', 'Pap', 44, 'test2@opx.hu'
);

INSERT INTO USER_AUTH_DETAILS VALUES (
  'user2', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_USER'
);
INSERT INTO USER_DETAILS VALUES (
  'user2', 'Attila', 'Kovacs', 33, 'test3@opx.hu'
);

INSERT INTO USER_AUTH_DETAILS VALUES (
  'user3', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_USER'
);
INSERT INTO USER_DETAILS VALUES (
  'user3', 'Miklos', 'Nagy', 15, 'test4@opx.hu'
);

INSERT INTO USER_AUTH_DETAILS VALUES (
  'user4', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_USER'
);
INSERT INTO USER_DETAILS VALUES (
  'user4', 'David', 'Varadi', 50, 'test5@opx.hu'
);

INSERT INTO USER_AUTH_DETAILS VALUES (
  'user5', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_USER'
);
INSERT INTO USER_DETAILS VALUES (
  'user5', 'Jozsef', 'Almasi', 44, 'test6@opx.hu'
);

INSERT INTO USER_AUTH_DETAILS VALUES (
  'user6', '$2a$04$BT2NWmlIgbX.OWtOwSlmpO3U3bQ5r/8Gd96WmrL112.SYqUSiiCNm', 'ROLE_USER'
);
INSERT INTO USER_DETAILS VALUES (
  'user6', 'Ferenc', 'Kis', 30, 'test7@opx.hu'
);