DROP TABLE IF EXISTS USR_RESET_PW_TOKEN;

DROP TABLE IF EXISTS ROL_ROLE;
CREATE TABLE ROL_ROLE (
  ROLE VARCHAR (15) NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS USR_ROLE;
CREATE TABLE USR_ROLE (
  USERNAME VARCHAR(20) NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USR_USER(USERNAME),
  FOREIGN KEY (ROLE) REFERENCES ROL_ROLE(ROLE)

);

DROP TABLE IF EXISTS USR_USER;
CREATE TABLE USR_USER (
  USERNAME VARCHAR(20) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR(100) NOT NULL,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(10) NOT NULL,
  AGE INT(2) NOT NULL,
  EMAILADDRESS VARCHAR(60) NOT NULL UNIQUE
);