DROP TABLE IF EXISTS USER_AUTH_DETAILS;
CREATE TABLE USER_AUTH_DETAILS (
  USERNAME VARCHAR(20) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR(100) NOT NULL,
  ROLE VARCHAR(10) NOT NULL
);
DROP TABLE IF EXISTS USER_DETAILS;
CREATE TABLE USER_DETAILS (
  USERNAME VARCHAR(20) NOT NULL PRIMARY KEY,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(10) NOT NULL,
  AGE INT(2) NOT NULL,
  EMAILADDRESS VARCHAR(60) NOT NULL UNIQUE
);